server.port: ${SERVER_PORT}
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_SUPPLIER}:3306/financial_proposals?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    format-sql: true
    hibernate.ddl-auto: update
  security.oauth2.resourceserver.jwt:
    issuer-uri: http://${KEYCLOAK_SUPPLIER:localhost}:18080/auth/realms/propostas
    jwk-set-uri: http://${KEYCLOAK_SUPPLIER:localhost}:18080/auth/realms/propostas/protocol/openid-connect/certs

management:
  endpoints:
    web.exposure.include: health, prometheus, info
    metrics.enabled: false
    prometheus.enabled: true
  metrics.tags:
    app: ${APP_NAME:proposals}
    env: ${ENV_NAME:dev}


# feign

feign:
  hystrix.enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

api:
  account.url: ${ACCOUNT_API:localhost}:8888
  analysis.url: ${ANALYSIS_API:localhost}:9999

# keycloak
auth:
  client_id: proposals
  client_secret: f6e9c65d-9c80-4ca4-adeb-6ad3e7dfda2d
  uri: http://${KEYCLOAK_SUPPLIER:localhost}:18080/auth/realms/propostas/protocol/openid-connect/token
  grant_type: password
  scope: openid